-- ============================================================================
-- Backfill placeholder customer phone numbers from contacts_extracted.xlsx
-- Review this file before running it. Not part of the numbered migration chain —
-- run once manually in the Supabase SQL editor (or `supabase db execute -f ...`).
-- Matching happens live against whatever is currently in `customers` — only rows
-- with a placeholder phone (phone LIKE 'NA%') are touched; real numbers are never
-- overwritten.
-- ============================================================================
begin;

-- ---- HIGH CONFIDENCE: matched by customer code (e.g. "C60") ----
update customers set phone = '9943777401', updated_at = now() where upper(trim(name)) = 'C67' and phone like 'NA%';
update customers set phone = '9500563340', updated_at = now() where upper(trim(name)) = 'C43' and phone like 'NA%';
update customers set phone = '6382640435', updated_at = now() where upper(trim(name)) = 'C80' and phone like 'NA%';
update customers set phone = '9025518795', updated_at = now() where upper(trim(name)) = 'C42' and phone like 'NA%';
update customers set phone = '9626041507', updated_at = now() where upper(trim(name)) = 'C51' and phone like 'NA%';
update customers set phone = '8122820082', updated_at = now() where upper(trim(name)) = 'C38' and phone like 'NA%';
update customers set phone = '9994241481', updated_at = now() where upper(trim(name)) = 'C71' and phone like 'NA%';
update customers set phone = '8825407064', updated_at = now() where upper(trim(name)) = 'C3' and phone like 'NA%';
update customers set phone = '7538808647', updated_at = now() where upper(trim(name)) = 'C36' and phone like 'NA%';
update customers set phone = '9092222618', updated_at = now() where upper(trim(name)) = 'C14' and phone like 'NA%';
update customers set phone = '9443328722', updated_at = now() where upper(trim(name)) = 'C78' and phone like 'NA%';
update customers set phone = '9894523034', updated_at = now() where upper(trim(name)) = 'C20' and phone like 'NA%';
update customers set phone = '8220801537', updated_at = now() where upper(trim(name)) = 'C61' and phone like 'NA%';
update customers set phone = '9787392455', updated_at = now() where upper(trim(name)) = 'C85' and phone like 'NA%';
update customers set phone = '9943671996', updated_at = now() where upper(trim(name)) = 'C12' and phone like 'NA%';
update customers set phone = '9790198726', updated_at = now() where upper(trim(name)) = 'C21' and phone like 'NA%';
update customers set phone = '9843779591', updated_at = now() where upper(trim(name)) = 'C56' and phone like 'NA%';
update customers set phone = '9989804384', updated_at = now() where upper(trim(name)) = 'C82' and phone like 'NA%';
update customers set phone = '9677304750', alt_phone = coalesce(alt_phone, '9790981804'), updated_at = now() where upper(trim(name)) = 'C33' and phone like 'NA%';
update customers set phone = '9994191847', updated_at = now() where upper(trim(name)) = 'C8' and phone like 'NA%';
update customers set phone = '9840999832', updated_at = now() where upper(trim(name)) = 'C53' and phone like 'NA%';
update customers set phone = '9600883477', updated_at = now() where upper(trim(name)) = 'C65' and phone like 'NA%';
update customers set phone = '9344535728', updated_at = now() where upper(trim(name)) = 'C81' and phone like 'NA%';
update customers set phone = '8220685757', updated_at = now() where upper(trim(name)) = 'C16' and phone like 'NA%';
update customers set phone = '9626656468', updated_at = now() where upper(trim(name)) = 'C66' and phone like 'NA%';
update customers set phone = '9176606409', updated_at = now() where upper(trim(name)) = 'C49' and phone like 'NA%';
update customers set phone = '9626218122', updated_at = now() where upper(trim(name)) = 'C98' and phone like 'NA%';
update customers set phone = '9025900571', updated_at = now() where upper(trim(name)) = 'C119' and phone like 'NA%';
update customers set phone = '9626717486', updated_at = now() where upper(trim(name)) = 'C126' and phone like 'NA%';
update customers set phone = '8428616541', updated_at = now() where upper(trim(name)) = 'C133' and phone like 'NA%';
update customers set phone = '9600388767', updated_at = now() where upper(trim(name)) = 'C140' and phone like 'NA%';
update customers set phone = '7639438111', updated_at = now() where upper(trim(name)) = 'C146' and phone like 'NA%';
update customers set phone = '9677873300', updated_at = now() where upper(trim(name)) = 'C15' and phone like 'NA%';
update customers set phone = '9952051195', updated_at = now() where upper(trim(name)) = 'C10' and phone like 'NA%';
update customers set phone = '9380896420', updated_at = now() where upper(trim(name)) = 'C162' and phone like 'NA%';
update customers set phone = '9095227854', updated_at = now() where upper(trim(name)) = 'C168' and phone like 'NA%';
update customers set phone = '9865385344', alt_phone = coalesce(alt_phone, '9003352238'), updated_at = now() where upper(trim(name)) = 'C174' and phone like 'NA%';
update customers set phone = '9751352981', updated_at = now() where upper(trim(name)) = 'C182' and phone like 'NA%';
update customers set phone = '9786851236', updated_at = now() where upper(trim(name)) = 'C183' and phone like 'NA%';
update customers set phone = '7904906295', updated_at = now() where upper(trim(name)) = 'C184' and phone like 'NA%';
update customers set phone = '6382833516', updated_at = now() where upper(trim(name)) = 'C193' and phone like 'NA%';
update customers set phone = '8939344408', updated_at = now() where upper(trim(name)) = 'C195' and phone like 'NA%';
update customers set phone = '9566312643', updated_at = now() where upper(trim(name)) = 'C202' and phone like 'NA%';
update customers set phone = '6381973695', updated_at = now() where upper(trim(name)) = 'C205' and phone like 'NA%';
update customers set phone = '6383716329', updated_at = now() where upper(trim(name)) = 'C207' and phone like 'NA%';
update customers set phone = '7339378263', updated_at = now() where upper(trim(name)) = 'C206' and phone like 'NA%';
update customers set phone = '9894258689', updated_at = now() where upper(trim(name)) = 'C209' and phone like 'NA%';
update customers set phone = '8056392509', updated_at = now() where upper(trim(name)) = 'C215' and phone like 'NA%';
update customers set phone = '9786896146', updated_at = now() where upper(trim(name)) = 'C47' and phone like 'NA%';
update customers set phone = '9790074938', alt_phone = coalesce(alt_phone, '9600224804'), updated_at = now() where upper(trim(name)) = 'C39' and phone like 'NA%';
update customers set phone = '9150801599', updated_at = now() where upper(trim(name)) = 'C87' and phone like 'NA%';
update customers set phone = '9500369568', updated_at = now() where upper(trim(name)) = 'C147' and phone like 'NA%';
update customers set phone = '8015793539', updated_at = now() where upper(trim(name)) = 'C148' and phone like 'NA%';
update customers set phone = '9677631490', updated_at = now() where upper(trim(name)) = 'C198' and phone like 'NA%';
update customers set phone = '9677802010', updated_at = now() where upper(trim(name)) = 'C179' and phone like 'NA%';
update customers set phone = '8807760414', updated_at = now() where upper(trim(name)) = 'C161' and phone like 'NA%';
update customers set phone = '9655976701', updated_at = now() where upper(trim(name)) = 'C186' and phone like 'NA%';
update customers set phone = '7871598473', updated_at = now() where upper(trim(name)) = 'C136' and phone like 'NA%';
update customers set phone = '9942447744', updated_at = now() where upper(trim(name)) = 'C105' and phone like 'NA%';
update customers set phone = '9042744695', updated_at = now() where upper(trim(name)) = 'C110' and phone like 'NA%';
update customers set phone = '9524716066', updated_at = now() where upper(trim(name)) = 'C200' and phone like 'NA%';
update customers set phone = '9790174808', updated_at = now() where upper(trim(name)) = 'C130' and phone like 'NA%';
update customers set phone = '9600093643', updated_at = now() where upper(trim(name)) = 'C187' and phone like 'NA%';
update customers set phone = '9751913476', updated_at = now() where upper(trim(name)) = 'C226' and phone like 'NA%';
update customers set phone = '8883344881', updated_at = now() where upper(trim(name)) = 'C224' and phone like 'NA%';
update customers set phone = '7904952144', updated_at = now() where upper(trim(name)) = 'C225' and phone like 'NA%';
update customers set phone = '9597727027', updated_at = now() where upper(trim(name)) = 'C230' and phone like 'NA%';
update customers set phone = '9952423326', updated_at = now() where upper(trim(name)) = 'C228' and phone like 'NA%';
update customers set phone = '9486268042', updated_at = now() where upper(trim(name)) = 'C231' and phone like 'NA%';
update customers set phone = '9543300070', updated_at = now() where upper(trim(name)) = 'C237' and phone like 'NA%';
update customers set phone = '9791279071', updated_at = now() where upper(trim(name)) = 'C238' and phone like 'NA%';
update customers set phone = '9080382308', updated_at = now() where upper(trim(name)) = 'C244' and phone like 'NA%';
update customers set phone = '9791547060', updated_at = now() where upper(trim(name)) = 'C245' and phone like 'NA%';
update customers set phone = '9790768207', updated_at = now() where upper(trim(name)) = 'C255' and phone like 'NA%';
update customers set phone = '9791718380', updated_at = now() where upper(trim(name)) = 'C258' and phone like 'NA%';
update customers set phone = '8220588551', updated_at = now() where upper(trim(name)) = 'C262' and phone like 'NA%';
update customers set phone = '9003885222', updated_at = now() where upper(trim(name)) = 'C263' and phone like 'NA%';
update customers set phone = '7899015908', updated_at = now() where upper(trim(name)) = 'C265' and phone like 'NA%';
update customers set phone = '8807194596', updated_at = now() where upper(trim(name)) = 'C266' and phone like 'NA%';
update customers set phone = '9952960073', updated_at = now() where upper(trim(name)) = 'C6' and phone like 'NA%';
update customers set phone = '8282828906', updated_at = now() where upper(trim(name)) = 'C122' and phone like 'NA%';
update customers set phone = '9944464138', updated_at = now() where upper(trim(name)) = 'C241' and phone like 'NA%';
update customers set phone = '9843151919', updated_at = now() where upper(trim(name)) = 'C274' and phone like 'NA%';
update customers set phone = '9360215386', updated_at = now() where upper(trim(name)) = 'C277' and phone like 'NA%';
update customers set phone = '9840556872', updated_at = now() where upper(trim(name)) = 'C275' and phone like 'NA%';
update customers set phone = '9940286127', updated_at = now() where upper(trim(name)) = 'C267' and phone like 'NA%';
update customers set phone = '9994458622', updated_at = now() where upper(trim(name)) = 'C295' and phone like 'NA%';
update customers set phone = '9791579731', updated_at = now() where upper(trim(name)) = 'C296' and phone like 'NA%';
update customers set phone = '7904322973', updated_at = now() where upper(trim(name)) = 'C214' and phone like 'NA%';
update customers set phone = '9677570071', updated_at = now() where upper(trim(name)) = 'C256' and phone like 'NA%';
update customers set phone = '9003569411', updated_at = now() where upper(trim(name)) = 'C70' and phone like 'NA%';
update customers set phone = '9597333211', updated_at = now() where upper(trim(name)) = 'C240' and phone like 'NA%';
update customers set phone = '8870660737', updated_at = now() where upper(trim(name)) = 'C189' and phone like 'NA%';
update customers set phone = '6381764143', updated_at = now() where upper(trim(name)) = 'C305' and phone like 'NA%';
update customers set phone = '9894895948', updated_at = now() where upper(trim(name)) = 'C197' and phone like 'NA%';
update customers set phone = '9080350659', updated_at = now() where upper(trim(name)) = 'C306' and phone like 'NA%';
update customers set phone = '7397276879', updated_at = now() where upper(trim(name)) = 'C307' and phone like 'NA%';
update customers set phone = '9786628413', updated_at = now() where upper(trim(name)) = 'C308' and phone like 'NA%';
update customers set phone = '7200334473', updated_at = now() where upper(trim(name)) = 'C124' and phone like 'NA%';
update customers set phone = '9786821040', updated_at = now() where upper(trim(name)) = 'C217' and phone like 'NA%';
update customers set phone = '9382712055', updated_at = now() where upper(trim(name)) = 'C288' and phone like 'NA%';
update customers set phone = '8056803929', updated_at = now() where upper(trim(name)) = 'C30' and phone like 'NA%';
update customers set phone = '9025666499', updated_at = now() where upper(trim(name)) = 'C5' and phone like 'NA%';
update customers set phone = '9944724045', updated_at = now() where upper(trim(name)) = 'C141' and phone like 'NA%';
update customers set phone = '9003403464', updated_at = now() where upper(trim(name)) = 'C97' and phone like 'NA%';
update customers set phone = '8608722367', updated_at = now() where upper(trim(name)) = 'C185' and phone like 'NA%';
update customers set phone = '8072663522', updated_at = now() where upper(trim(name)) = 'C155' and phone like 'NA%';
update customers set phone = '9787478212', updated_at = now() where upper(trim(name)) = 'C113' and phone like 'NA%';
update customers set phone = '6382513580', alt_phone = coalesce(alt_phone, '6380841762'), updated_at = now() where upper(trim(name)) = 'C173' and phone like 'NA%';
update customers set phone = '9791970616', alt_phone = coalesce(alt_phone, '9092847751'), updated_at = now() where upper(trim(name)) = 'C24' and phone like 'NA%';
update customers set phone = '9791309595', updated_at = now() where upper(trim(name)) = 'C91' and phone like 'NA%';
update customers set phone = '9952968009', updated_at = now() where upper(trim(name)) = 'C175' and phone like 'NA%';
update customers set phone = '9500507758', updated_at = now() where upper(trim(name)) = 'C212' and phone like 'NA%';
update customers set phone = '8122120100', updated_at = now() where upper(trim(name)) = 'C4' and phone like 'NA%';
update customers set phone = '6382300454', updated_at = now() where upper(trim(name)) = 'C69' and phone like 'NA%';
update customers set phone = '9940813001', updated_at = now() where upper(trim(name)) = 'C144' and phone like 'NA%';
update customers set phone = '6380896833', alt_phone = coalesce(alt_phone, '9791326723'), updated_at = now() where upper(trim(name)) = 'C153' and phone like 'NA%';
update customers set phone = '9514261283', updated_at = now() where upper(trim(name)) = 'C68' and phone like 'NA%';
update customers set phone = '9962383325', updated_at = now() where upper(trim(name)) = 'C294' and phone like 'NA%';
update customers set phone = '7358979436', updated_at = now() where upper(trim(name)) = 'C134' and phone like 'NA%';
update customers set phone = '9786374311', updated_at = now() where upper(trim(name)) = 'C199' and phone like 'NA%';
update customers set phone = '9003136968', updated_at = now() where upper(trim(name)) = 'C88' and phone like 'NA%';
update customers set phone = '9944363855', alt_phone = coalesce(alt_phone, '8220426155'), updated_at = now() where upper(trim(name)) = 'C90' and phone like 'NA%';
update customers set phone = '9791242274', updated_at = now() where upper(trim(name)) = 'C208' and phone like 'NA%';
update customers set phone = '9629952204', updated_at = now() where upper(trim(name)) = 'C77' and phone like 'NA%';
update customers set phone = '9944008074', updated_at = now() where upper(trim(name)) = 'C269' and phone like 'NA%';
update customers set phone = '6369553379', updated_at = now() where upper(trim(name)) = 'C99' and phone like 'NA%';
update customers set phone = '8428444289', updated_at = now() where upper(trim(name)) = 'C272' and phone like 'NA%';
update customers set phone = '9940777335', updated_at = now() where upper(trim(name)) = 'C31' and phone like 'NA%';
update customers set phone = '9025346207', updated_at = now() where upper(trim(name)) = 'C54' and phone like 'NA%';
update customers set phone = '9047800769', updated_at = now() where upper(trim(name)) = 'C239' and phone like 'NA%';
update customers set phone = '9965145479', updated_at = now() where upper(trim(name)) = 'C35' and phone like 'NA%';
update customers set phone = '9092555732', updated_at = now() where upper(trim(name)) = 'C75' and phone like 'NA%';
update customers set phone = '9442575357', updated_at = now() where upper(trim(name)) = 'C72' and phone like 'NA%';
update customers set phone = '8939528899', updated_at = now() where upper(trim(name)) = 'C293' and phone like 'NA%';
update customers set phone = '9944223713', updated_at = now() where upper(trim(name)) = 'C169' and phone like 'NA%';
update customers set phone = '9043566690', updated_at = now() where upper(trim(name)) = 'C317' and phone like 'NA%';
update customers set phone = '9787011474', updated_at = now() where upper(trim(name)) = 'C299' and phone like 'NA%';
update customers set phone = '9498146305', updated_at = now() where upper(trim(name)) = 'C125' and phone like 'NA%';
update customers set phone = '8838533277', updated_at = now() where upper(trim(name)) = 'C165' and phone like 'NA%';
update customers set phone = '9003028462', updated_at = now() where upper(trim(name)) = 'C254' and phone like 'NA%';
update customers set phone = '9841224072', updated_at = now() where upper(trim(name)) = 'C222' and phone like 'NA%';
update customers set phone = '8220591961', updated_at = now() where upper(trim(name)) = 'C218' and phone like 'NA%';
update customers set phone = '9842084685', updated_at = now() where upper(trim(name)) = 'C2' and phone like 'NA%';
update customers set phone = '9940197494', updated_at = now() where upper(trim(name)) = 'C227' and phone like 'NA%';
update customers set phone = '8870444249', updated_at = now() where upper(trim(name)) = 'C158' and phone like 'NA%';
update customers set phone = '8940003028', updated_at = now() where upper(trim(name)) = 'C261' and phone like 'NA%';
update customers set phone = '9444092202', updated_at = now() where upper(trim(name)) = 'C131' and phone like 'NA%';
update customers set phone = '7871113424', updated_at = now() where upper(trim(name)) = 'C95' and phone like 'NA%';
update customers set phone = '8608386636', updated_at = now() where upper(trim(name)) = 'C22' and phone like 'NA%';
update customers set phone = '8940822351', updated_at = now() where upper(trim(name)) = 'C315' and phone like 'NA%';
update customers set phone = '8098922730', updated_at = now() where upper(trim(name)) = 'C18' and phone like 'NA%';
update customers set phone = '8680801299', updated_at = now() where upper(trim(name)) = 'C246' and phone like 'NA%';
update customers set phone = '8825724345', updated_at = now() where upper(trim(name)) = 'C111' and phone like 'NA%';
update customers set phone = '9738989394', updated_at = now() where upper(trim(name)) = 'C143' and phone like 'NA%';
update customers set phone = '7708207835', updated_at = now() where upper(trim(name)) = 'C236' and phone like 'NA%';
update customers set phone = '9952897894', updated_at = now() where upper(trim(name)) = 'C309' and phone like 'NA%';
update customers set phone = '9710047560', updated_at = now() where upper(trim(name)) = 'C76' and phone like 'NA%';
update customers set phone = '9489400847', updated_at = now() where upper(trim(name)) = 'C151' and phone like 'NA%';
update customers set phone = '9443110100', updated_at = now() where upper(trim(name)) = 'C192' and phone like 'NA%';
update customers set phone = '9944995373', updated_at = now() where upper(trim(name)) = 'C178' and phone like 'NA%';
update customers set phone = '9789702065', alt_phone = coalesce(alt_phone, '8825504918'), updated_at = now() where upper(trim(name)) = 'C60' and phone like 'NA%';
update customers set phone = '8825935867', updated_at = now() where upper(trim(name)) = 'C1' and phone like 'NA%';
update customers set phone = '7868053270', updated_at = now() where upper(trim(name)) = 'C101' and phone like 'NA%';
update customers set phone = '9171404798', updated_at = now() where upper(trim(name)) = 'C166' and phone like 'NA%';
update customers set phone = '6379727180', updated_at = now() where upper(trim(name)) = 'C213' and phone like 'NA%';
update customers set phone = '8778743004', updated_at = now() where upper(trim(name)) = 'C273' and phone like 'NA%';
update customers set phone = '9498405727', updated_at = now() where upper(trim(name)) = 'C292' and phone like 'NA%';
update customers set phone = '9944435363', updated_at = now() where upper(trim(name)) = 'C324' and phone like 'NA%';
update customers set phone = '9080581703', updated_at = now() where upper(trim(name)) = 'C323' and phone like 'NA%';
update customers set phone = '9445144700', alt_phone = coalesce(alt_phone, '7845606727'), updated_at = now() where upper(trim(name)) = 'C7' and phone like 'NA%';
update customers set phone = '6383163775', updated_at = now() where upper(trim(name)) = 'C219' and phone like 'NA%';
update customers set phone = '9677091421', updated_at = now() where upper(trim(name)) = 'C325' and phone like 'NA%';
update customers set phone = '7448668003', updated_at = now() where upper(trim(name)) = 'C19' and phone like 'NA%';
update customers set phone = '7358604985', updated_at = now() where upper(trim(name)) = 'C28' and phone like 'NA%';
update customers set phone = '9566373672', updated_at = now() where upper(trim(name)) = 'C177' and phone like 'NA%';
update customers set phone = '9043242930', updated_at = now() where upper(trim(name)) = 'C62' and phone like 'NA%';
update customers set phone = '9940909381', updated_at = now() where upper(trim(name)) = 'C276' and phone like 'NA%';
update customers set phone = '8072340323', updated_at = now() where upper(trim(name)) = 'C156' and phone like 'NA%';
update customers set phone = '8122441789', updated_at = now() where upper(trim(name)) = 'C327' and phone like 'NA%';
update customers set phone = '7871895464', updated_at = now() where upper(trim(name)) = 'C232' and phone like 'NA%';
update customers set phone = '8940109336', updated_at = now() where upper(trim(name)) = 'C223' and phone like 'NA%';
update customers set phone = '6381252185', updated_at = now() where upper(trim(name)) = 'C271' and phone like 'NA%';
update customers set phone = '9842095553', updated_at = now() where upper(trim(name)) = 'C328' and phone like 'NA%';
update customers set phone = '9003213376', updated_at = now() where upper(trim(name)) = 'C291' and phone like 'NA%';
update customers set phone = '9994193305', updated_at = now() where upper(trim(name)) = 'C115' and phone like 'NA%';
update customers set phone = '8056440291', updated_at = now() where upper(trim(name)) = 'C297' and phone like 'NA%';
update customers set phone = '9715380045', alt_phone = coalesce(alt_phone, '6383304307'), updated_at = now() where upper(trim(name)) = 'C41' and phone like 'NA%';
update customers set phone = '9843568775', updated_at = now() where upper(trim(name)) = 'C157' and phone like 'NA%';
update customers set phone = '9445406887', updated_at = now() where upper(trim(name)) = 'C160' and phone like 'NA%';
update customers set phone = '8220561607', updated_at = now() where upper(trim(name)) = 'C25' and phone like 'NA%';
update customers set phone = '8072837742', updated_at = now() where upper(trim(name)) = 'C128' and phone like 'NA%';
update customers set phone = '8754688430', updated_at = now() where upper(trim(name)) = 'C44' and phone like 'NA%';
update customers set phone = '7904215454', updated_at = now() where upper(trim(name)) = 'C118' and phone like 'NA%';
update customers set phone = '9003272090', updated_at = now() where upper(trim(name)) = 'C264' and phone like 'NA%';
update customers set phone = '8015444714', updated_at = now() where upper(trim(name)) = 'C73' and phone like 'NA%';
update customers set phone = '7010367943', updated_at = now() where upper(trim(name)) = 'C120' and phone like 'NA%';
update customers set phone = '9443278483', updated_at = now() where upper(trim(name)) = 'C50' and phone like 'NA%';
update customers set phone = '9500065224', updated_at = now() where upper(trim(name)) = 'C127' and phone like 'NA%';
update customers set phone = '6369984349', updated_at = now() where upper(trim(name)) = 'C48' and phone like 'NA%';
update customers set phone = '7449130874', updated_at = now() where upper(trim(name)) = 'C108' and phone like 'NA%';
update customers set phone = '6382977691', updated_at = now() where upper(trim(name)) = 'C320' and phone like 'NA%';
update customers set phone = '9080336394', alt_phone = coalesce(alt_phone, '9894297336'), updated_at = now() where upper(trim(name)) = 'C302' and phone like 'NA%';
update customers set phone = '7845256920', updated_at = now() where upper(trim(name)) = 'C181' and phone like 'NA%';
update customers set phone = '9994524019', updated_at = now() where upper(trim(name)) = 'C116' and phone like 'NA%';
update customers set phone = '9789291922', updated_at = now() where upper(trim(name)) = 'C303' and phone like 'NA%';
update customers set phone = '9940389558', updated_at = now() where upper(trim(name)) = 'C301' and phone like 'NA%';
update customers set phone = '9710597637', updated_at = now() where upper(trim(name)) = 'C107' and phone like 'NA%';
update customers set phone = '9585955660', updated_at = now() where upper(trim(name)) = 'C335' and phone like 'NA%';
update customers set phone = '8825831900', updated_at = now() where upper(trim(name)) = 'C211' and phone like 'NA%';
update customers set phone = '9003158194', updated_at = now() where upper(trim(name)) = 'C55' and phone like 'NA%';
update customers set phone = '9943238298', updated_at = now() where upper(trim(name)) = 'C64' and phone like 'NA%';
update customers set phone = '9790566011', updated_at = now() where upper(trim(name)) = 'C171' and phone like 'NA%';
update customers set phone = '9042472011', updated_at = now() where upper(trim(name)) = 'C330' and phone like 'NA%';
update customers set phone = '9965944039', updated_at = now() where upper(trim(name)) = 'C270' and phone like 'NA%';
update customers set phone = '8098179035', updated_at = now() where upper(trim(name)) = 'C167' and phone like 'NA%';
update customers set phone = '9003545557', updated_at = now() where upper(trim(name)) = 'C247' and phone like 'NA%';
update customers set phone = '8940056749', updated_at = now() where upper(trim(name)) = 'C58' and phone like 'NA%';
update customers set phone = '9500002879', updated_at = now() where upper(trim(name)) = 'C102' and phone like 'NA%';
update customers set phone = '8489845961', updated_at = now() where upper(trim(name)) = 'C332' and phone like 'NA%';
update customers set phone = '9944814951', updated_at = now() where upper(trim(name)) = 'C45' and phone like 'NA%';
update customers set phone = '8939117225', updated_at = now() where upper(trim(name)) = 'C235' and phone like 'NA%';
update customers set phone = '7418253838', updated_at = now() where upper(trim(name)) = 'C74' and phone like 'NA%';
update customers set phone = '9943610808', updated_at = now() where upper(trim(name)) = 'C243' and phone like 'NA%';
update customers set phone = '9940840768', updated_at = now() where upper(trim(name)) = 'C132' and phone like 'NA%';
update customers set phone = '9943612405', updated_at = now() where upper(trim(name)) = 'C86' and phone like 'NA%';
update customers set phone = '8925629824', updated_at = now() where upper(trim(name)) = 'C340' and phone like 'NA%';
update customers set phone = '9566662957', updated_at = now() where upper(trim(name)) = 'C341' and phone like 'NA%';
update customers set phone = '9003860730', updated_at = now() where upper(trim(name)) = 'C304' and phone like 'NA%';
update customers set phone = '9994562051', updated_at = now() where upper(trim(name)) = 'C251' and phone like 'NA%';
update customers set phone = '9600070311', updated_at = now() where upper(trim(name)) = 'C321' and phone like 'NA%';
update customers set phone = '9884561886', updated_at = now() where upper(trim(name)) = 'C92' and phone like 'NA%';
update customers set phone = '9094003870', updated_at = now() where upper(trim(name)) = 'C268' and phone like 'NA%';
update customers set phone = '9043199128', updated_at = now() where upper(trim(name)) = 'C310' and phone like 'NA%';
update customers set phone = '8489369654', updated_at = now() where upper(trim(name)) = 'C84' and phone like 'NA%';
update customers set phone = '8122249498', updated_at = now() where upper(trim(name)) = 'C344' and phone like 'NA%';
update customers set phone = '7373839595', updated_at = now() where upper(trim(name)) = 'C343' and phone like 'NA%';
update customers set phone = '9994832815', alt_phone = coalesce(alt_phone, '6369364351'), updated_at = now() where upper(trim(name)) = 'C338' and phone like 'NA%';
update customers set phone = '9994715498', updated_at = now() where upper(trim(name)) = 'C93' and phone like 'NA%';
update customers set phone = '9843092561', updated_at = now() where upper(trim(name)) = 'C17' and phone like 'NA%';
update customers set phone = '9344696818', updated_at = now() where upper(trim(name)) = 'C34' and phone like 'NA%';
update customers set phone = '8838352928', updated_at = now() where upper(trim(name)) = 'C318' and phone like 'NA%';
update customers set phone = '8838787380', updated_at = now() where upper(trim(name)) = 'C149' and phone like 'NA%';
update customers set phone = '9025749993', updated_at = now() where upper(trim(name)) = 'C350' and phone like 'NA%';
update customers set phone = '6374229660', updated_at = now() where upper(trim(name)) = 'C345' and phone like 'NA%';
update customers set phone = '9791399475', updated_at = now() where upper(trim(name)) = 'C13' and phone like 'NA%';
update customers set phone = '8754510293', updated_at = now() where upper(trim(name)) = 'C351' and phone like 'NA%';
update customers set phone = '8825544411', updated_at = now() where upper(trim(name)) = 'C163' and phone like 'NA%';
update customers set phone = '8015143136', updated_at = now() where upper(trim(name)) = 'C347' and phone like 'NA%';
update customers set phone = '9942347023', updated_at = now() where upper(trim(name)) = 'C342' and phone like 'NA%';
update customers set phone = '8682992611', updated_at = now() where upper(trim(name)) = 'C362' and phone like 'NA%';
update customers set phone = '9940862562', updated_at = now() where upper(trim(name)) = 'C129' and phone like 'NA%';
update customers set phone = '7402407000', updated_at = now() where upper(trim(name)) = 'C63' and phone like 'NA%';
update customers set phone = '9952709376', updated_at = now() where upper(trim(name)) = 'C260' and phone like 'NA%';
update customers set phone = '9080333313', updated_at = now() where upper(trim(name)) = 'C354' and phone like 'NA%';
update customers set phone = '9629921142', updated_at = now() where upper(trim(name)) = 'C353' and phone like 'NA%';
update customers set phone = '9047483750', updated_at = now() where upper(trim(name)) = 'C104' and phone like 'NA%';
update customers set phone = '9940309749', updated_at = now() where upper(trim(name)) = 'C319' and phone like 'NA%';
update customers set phone = '8668065630', updated_at = now() where upper(trim(name)) = 'C313' and phone like 'NA%';
update customers set phone = '6382490865', updated_at = now() where upper(trim(name)) = 'C188' and phone like 'NA%';
update customers set phone = '8072856361', updated_at = now() where upper(trim(name)) = 'C322' and phone like 'NA%';
update customers set phone = '8122420566', updated_at = now() where upper(trim(name)) = 'C346' and phone like 'NA%';
update customers set phone = '9943166006', updated_at = now() where upper(trim(name)) = 'C11' and phone like 'NA%';
update customers set phone = '9159420432', updated_at = now() where upper(trim(name)) = 'C352' and phone like 'NA%';
update customers set phone = '9894294288', updated_at = now() where upper(trim(name)) = 'C150' and phone like 'NA%';
update customers set phone = '8608616474', updated_at = now() where upper(trim(name)) = 'C40' and phone like 'NA%';
update customers set phone = '8428547864', updated_at = now() where upper(trim(name)) = 'C242' and phone like 'NA%';
update customers set phone = '9894534213', updated_at = now() where upper(trim(name)) = 'C210' and phone like 'NA%';
update customers set phone = '9176628573', updated_at = now() where upper(trim(name)) = 'C172' and phone like 'NA%';
update customers set phone = '9840494662', updated_at = now() where upper(trim(name)) = 'C176' and phone like 'NA%';
update customers set phone = '8610758703', updated_at = now() where upper(trim(name)) = 'C32' and phone like 'NA%';
update customers set phone = '7708023041', updated_at = now() where upper(trim(name)) = 'C334' and phone like 'NA%';
update customers set phone = '9363396091', updated_at = now() where upper(trim(name)) = 'C333' and phone like 'NA%';
update customers set phone = '9942006669', updated_at = now() where upper(trim(name)) = 'C361' and phone like 'NA%';
update customers set phone = '7358394726', alt_phone = coalesce(alt_phone, '8608951784'), updated_at = now() where upper(trim(name)) = 'C103' and phone like 'NA%';
update customers set phone = '7845610908', alt_phone = coalesce(alt_phone, '9655946647'), updated_at = now() where upper(trim(name)) = 'C337' and phone like 'NA%';
update customers set phone = '9597774534', updated_at = now() where upper(trim(name)) = 'C363' and phone like 'NA%';
update customers set phone = '6380200979', alt_phone = coalesce(alt_phone, '8124150921'), updated_at = now() where upper(trim(name)) = 'C339' and phone like 'NA%';
update customers set phone = '9244860960', updated_at = now() where upper(trim(name)) = 'C316' and phone like 'NA%';
update customers set phone = '9952495233', updated_at = now() where upper(trim(name)) = 'C194' and phone like 'NA%';
update customers set phone = '9176033386', updated_at = now() where upper(trim(name)) = 'C290' and phone like 'NA%';
update customers set phone = '8248412053', updated_at = now() where upper(trim(name)) = 'C142' and phone like 'NA%';
update customers set phone = '9566818001', updated_at = now() where upper(trim(name)) = 'C112' and phone like 'NA%';
update customers set phone = '6382305795', updated_at = now() where upper(trim(name)) = 'C114' and phone like 'NA%';
update customers set phone = '8248696700', alt_phone = coalesce(alt_phone, '7358489658'), updated_at = now() where upper(trim(name)) = 'C23' and phone like 'NA%';
update customers set phone = '9843459493', alt_phone = coalesce(alt_phone, '9944323221'), updated_at = now() where upper(trim(name)) = 'C356' and phone like 'NA%';
update customers set phone = '9843644827', alt_phone = coalesce(alt_phone, '9942918062'), updated_at = now() where upper(trim(name)) = 'C109' and phone like 'NA%';
update customers set phone = '9944271763', updated_at = now() where upper(trim(name)) = 'C191' and phone like 'NA%';
update customers set phone = '9942831070', updated_at = now() where upper(trim(name)) = 'C359' and phone like 'NA%';
update customers set phone = '9600540269', updated_at = now() where upper(trim(name)) = 'C221' and phone like 'NA%';
update customers set phone = '9677343434', updated_at = now() where upper(trim(name)) = 'C250' and phone like 'NA%';
update customers set phone = '9894083824', updated_at = now() where upper(trim(name)) = 'C364' and phone like 'NA%';
update customers set phone = '7708000430', updated_at = now() where upper(trim(name)) = 'C249' and phone like 'NA%';
update customers set phone = '8870212326', updated_at = now() where upper(trim(name)) = 'C159' and phone like 'NA%';
update customers set phone = '7780677579', updated_at = now() where upper(trim(name)) = 'C360' and phone like 'NA%';
update customers set phone = '9840773812', updated_at = now() where upper(trim(name)) = 'C139' and phone like 'NA%';
update customers set phone = '9360695757', updated_at = now() where upper(trim(name)) = 'C26' and phone like 'NA%';
update customers set phone = '7550056258', alt_phone = coalesce(alt_phone, '9884442572'), updated_at = now() where upper(trim(name)) = 'C216' and phone like 'NA%';
update customers set phone = '8667500484', updated_at = now() where upper(trim(name)) = 'C370' and phone like 'NA%';
update customers set phone = '9176323397', updated_at = now() where upper(trim(name)) = 'C368' and phone like 'NA%';
update customers set phone = '8248530101', updated_at = now() where upper(trim(name)) = 'C371' and phone like 'NA%';
update customers set phone = '9894597950', updated_at = now() where upper(trim(name)) = 'C369' and phone like 'NA%';
update customers set phone = '9944902583', updated_at = now() where upper(trim(name)) = 'C372' and phone like 'NA%';
update customers set phone = '7338760265', updated_at = now() where upper(trim(name)) = 'C248' and phone like 'NA%';
update customers set phone = '7871609943', updated_at = now() where upper(trim(name)) = 'C137' and phone like 'NA%';
update customers set phone = '6369845780', updated_at = now() where upper(trim(name)) = 'C358' and phone like 'NA%';
update customers set phone = '8668038622', updated_at = now() where upper(trim(name)) = 'C257' and phone like 'NA%';
update customers set phone = '8754106102', updated_at = now() where upper(trim(name)) = 'C123' and phone like 'NA%';
update customers set phone = '8489414116', updated_at = now() where upper(trim(name)) = 'C233' and phone like 'NA%';
update customers set phone = '9629471656', updated_at = now() where upper(trim(name)) = 'C100' and phone like 'NA%';
update customers set phone = '7603853176', updated_at = now() where upper(trim(name)) = 'C138' and phone like 'NA%';
update customers set phone = '9787888717', alt_phone = coalesce(alt_phone, '8883332511'), updated_at = now() where upper(trim(name)) = 'C196' and phone like 'NA%';
update customers set phone = '9025602739', updated_at = now() where upper(trim(name)) = 'C373' and phone like 'NA%';
update customers set phone = '9894105495', updated_at = now() where upper(trim(name)) = 'C135' and phone like 'NA%';
update customers set phone = '6382485952', updated_at = now() where upper(trim(name)) = 'C121' and phone like 'NA%';
update customers set phone = '9786489574', updated_at = now() where upper(trim(name)) = 'C201' and phone like 'NA%';
update customers set phone = '9790213037', updated_at = now() where upper(trim(name)) = 'C378' and phone like 'NA%';
update customers set phone = '9443277241', updated_at = now() where upper(trim(name)) = 'C376' and phone like 'NA%';
update customers set phone = '9841610594', updated_at = now() where upper(trim(name)) = 'C377' and phone like 'NA%';
update customers set phone = '9042384416', updated_at = now() where upper(trim(name)) = 'C379' and phone like 'NA%';
update customers set phone = '8667661489', updated_at = now() where upper(trim(name)) = 'C204' and phone like 'NA%';
update customers set phone = '9962203977', updated_at = now() where upper(trim(name)) = 'C253' and phone like 'NA%';
update customers set phone = '9790520322', updated_at = now() where upper(trim(name)) = 'C336' and phone like 'NA%';
update customers set phone = '6379742313', updated_at = now() where upper(trim(name)) = 'C382' and phone like 'NA%';
update customers set phone = '9790697411', updated_at = now() where upper(trim(name)) = 'C381' and phone like 'NA%';
update customers set phone = '8056641635', alt_phone = coalesce(alt_phone, '9500735481'), updated_at = now() where upper(trim(name)) = 'C329' and phone like 'NA%';
update customers set phone = '8220385151', updated_at = now() where upper(trim(name)) = 'C298' and phone like 'NA%';
update customers set phone = '9884951119', updated_at = now() where upper(trim(name)) = 'C190' and phone like 'NA%';
update customers set phone = '7358031932', updated_at = now() where upper(trim(name)) = 'C348' and phone like 'NA%';
update customers set phone = '9626664533', updated_at = now() where upper(trim(name)) = 'C365' and phone like 'NA%';
update customers set phone = '6374249766', updated_at = now() where upper(trim(name)) = 'C203' and phone like 'NA%';
update customers set phone = '9080902573', updated_at = now() where upper(trim(name)) = 'C384' and phone like 'NA%';
update customers set phone = '9443276938', updated_at = now() where upper(trim(name)) = 'C9' and phone like 'NA%';
update customers set phone = '8939849659', updated_at = now() where upper(trim(name)) = 'C94' and phone like 'NA%';
update customers set phone = '8608883051', updated_at = now() where upper(trim(name)) = 'C326' and phone like 'NA%';
update customers set phone = '8098266140', updated_at = now() where upper(trim(name)) = 'C387' and phone like 'NA%';
update customers set phone = '9994686945', updated_at = now() where upper(trim(name)) = 'C388' and phone like 'NA%';
update customers set phone = '9597904520', updated_at = now() where upper(trim(name)) = 'C389' and phone like 'NA%';
update customers set phone = '9443638593', updated_at = now() where upper(trim(name)) = 'C385' and phone like 'NA%';
update customers set phone = '9655531715', updated_at = now() where upper(trim(name)) = 'C375' and phone like 'NA%';
update customers set phone = '6382890252', updated_at = now() where upper(trim(name)) = 'C349' and phone like 'NA%';
update customers set phone = '9100988207', updated_at = now() where upper(trim(name)) = 'C391' and phone like 'NA%';
update customers set phone = '9941032079', updated_at = now() where upper(trim(name)) = 'C393' and phone like 'NA%';
update customers set phone = '7793944749', alt_phone = coalesce(alt_phone, '8248163763'), updated_at = now() where upper(trim(name)) = 'C392' and phone like 'NA%';
update customers set phone = '9600535484', updated_at = now() where upper(trim(name)) = 'C394' and phone like 'NA%';
update customers set phone = '9944182942', updated_at = now() where upper(trim(name)) = 'C380' and phone like 'NA%';
update customers set phone = '9597572746', updated_at = now() where upper(trim(name)) = 'C396' and phone like 'NA%';
update customers set phone = '8148391899', updated_at = now() where upper(trim(name)) = 'C355' and phone like 'NA%';
update customers set phone = '9626260007', updated_at = now() where upper(trim(name)) = 'C409' and phone like 'NA%';
update customers set phone = '7708678685', updated_at = now() where upper(trim(name)) = 'C397' and phone like 'NA%';
update customers set phone = '8220533794', updated_at = now() where upper(trim(name)) = 'C398' and phone like 'NA%';
update customers set phone = '8610613516', alt_phone = coalesce(alt_phone, '9952009323'), updated_at = now() where upper(trim(name)) = 'C399' and phone like 'NA%';
update customers set phone = '9944364685', updated_at = now() where upper(trim(name)) = 'C400' and phone like 'NA%';
update customers set phone = '9841508193', updated_at = now() where upper(trim(name)) = 'C59' and phone like 'NA%';
update customers set phone = '9629592943', updated_at = now() where upper(trim(name)) = 'C402' and phone like 'NA%';
update customers set phone = '9059488627', updated_at = now() where upper(trim(name)) = 'C367' and phone like 'NA%';
update customers set phone = '9980975943', updated_at = now() where upper(trim(name)) = 'C314' and phone like 'NA%';
update customers set phone = '9791550312', updated_at = now() where upper(trim(name)) = 'C164' and phone like 'NA%';
update customers set phone = '9566188137', updated_at = now() where upper(trim(name)) = 'C383' and phone like 'NA%';
update customers set phone = '9600682023', updated_at = now() where upper(trim(name)) = 'C145' and phone like 'NA%';
update customers set phone = '9003580448', alt_phone = coalesce(alt_phone, '7402902315'), updated_at = now() where upper(trim(name)) = 'C106' and phone like 'NA%';
update customers set phone = '9751521435', alt_phone = coalesce(alt_phone, '8680975995'), updated_at = now() where upper(trim(name)) = 'C311' and phone like 'NA%';
update customers set phone = '9715910737', updated_at = now() where upper(trim(name)) = 'C57' and phone like 'NA%';
update customers set phone = '9976140402', updated_at = now() where upper(trim(name)) = 'C27' and phone like 'NA%';
update customers set phone = '9443990052', updated_at = now() where upper(trim(name)) = 'C96' and phone like 'NA%';
update customers set phone = '9655189543', updated_at = now() where upper(trim(name)) = 'C403' and phone like 'NA%';
update customers set phone = '9092045793', updated_at = now() where upper(trim(name)) = 'C404' and phone like 'NA%';
update customers set phone = '8667078065', updated_at = now() where upper(trim(name)) = 'C357' and phone like 'NA%';
update customers set phone = '9361920932', updated_at = now() where upper(trim(name)) = 'C406' and phone like 'NA%';
update customers set phone = '9843586999', updated_at = now() where upper(trim(name)) = 'C366' and phone like 'NA%';
update customers set phone = '9042675101', updated_at = now() where upper(trim(name)) = 'C407' and phone like 'NA%';
update customers set phone = '9843569098', alt_phone = coalesce(alt_phone, '7418503949'), updated_at = now() where upper(trim(name)) = 'C234' and phone like 'NA%';
update customers set phone = '9600961777', updated_at = now() where upper(trim(name)) = 'C170' and phone like 'NA%';
update customers set phone = '8220188798', updated_at = now() where upper(trim(name)) = 'C386' and phone like 'NA%';
update customers set phone = '9360403428', updated_at = now() where upper(trim(name)) = 'C259' and phone like 'NA%';
update customers set phone = '8015989902', updated_at = now() where upper(trim(name)) = 'C408' and phone like 'NA%';
update customers set phone = '9597296458', updated_at = now() where upper(trim(name)) = 'C410' and phone like 'NA%';
update customers set phone = '8489347773', updated_at = now() where upper(trim(name)) = 'C180' and phone like 'NA%';
update customers set phone = '9786941495', updated_at = now() where upper(trim(name)) = 'C300' and phone like 'NA%';
update customers set phone = '8098564368', updated_at = now() where upper(trim(name)) = 'C220' and phone like 'NA%';
update customers set phone = '8667595821', updated_at = now() where upper(trim(name)) = 'C405' and phone like 'NA%';
update customers set phone = '9865299112', updated_at = now() where upper(trim(name)) = 'C390' and phone like 'NA%';
update customers set phone = '9894084111', updated_at = now() where upper(trim(name)) = 'C331' and phone like 'NA%';
update customers set phone = '9600092695', updated_at = now() where upper(trim(name)) = 'C414' and phone like 'NA%';
update customers set phone = '9500592958', updated_at = now() where upper(trim(name)) = 'C413' and phone like 'NA%';
update customers set phone = '9843347082', updated_at = now() where upper(trim(name)) = 'C411' and phone like 'NA%';
update customers set phone = '6385782209', updated_at = now() where upper(trim(name)) = 'C412' and phone like 'NA%';
update customers set phone = '9498086381', updated_at = now() where upper(trim(name)) = 'C415' and phone like 'NA%';
update customers set phone = '9786110188', updated_at = now() where upper(trim(name)) = 'C89' and phone like 'NA%';
update customers set phone = '9751638999', updated_at = now() where upper(trim(name)) = 'C395' and phone like 'NA%';
update customers set phone = '9500919557', updated_at = now() where upper(trim(name)) = 'C416' and phone like 'NA%';
update customers set phone = '7010747506', updated_at = now() where upper(trim(name)) = 'C417' and phone like 'NA%';
update customers set phone = '8682016910', updated_at = now() where upper(trim(name)) = 'C418' and phone like 'NA%';
update customers set phone = '9080591509', alt_phone = coalesce(alt_phone, '9444239582'), updated_at = now() where upper(trim(name)) = 'C46' and phone like 'NA%';
update customers set phone = '9025235151', updated_at = now() where upper(trim(name)) = 'C83' and phone like 'NA%';
update customers set phone = '9710011320', updated_at = now() where upper(trim(name)) = 'C252' and phone like 'NA%';
update customers set phone = '9597915969', updated_at = now() where upper(trim(name)) = 'C422' and phone like 'NA%';
update customers set phone = '8608158711', updated_at = now() where upper(trim(name)) = 'C419' and phone like 'NA%';
update customers set phone = '7708465734', updated_at = now() where upper(trim(name)) = 'C420' and phone like 'NA%';
update customers set phone = '8508621505', updated_at = now() where upper(trim(name)) = 'C421' and phone like 'NA%';
update customers set phone = '9003545945', updated_at = now() where upper(trim(name)) = 'C423' and phone like 'NA%';
update customers set phone = '9952979415', updated_at = now() where upper(trim(name)) = 'C424' and phone like 'NA%';
update customers set phone = '7708849096', updated_at = now() where upper(trim(name)) = 'C374' and phone like 'NA%';
update customers set phone = '9245625993', updated_at = now() where upper(trim(name)) = 'C154' and phone like 'NA%';
update customers set phone = '8754360158', alt_phone = coalesce(alt_phone, '7639467238'), updated_at = now() where upper(trim(name)) = 'C312' and phone like 'NA%';
update customers set phone = '8248471985', updated_at = now() where upper(trim(name)) = 'C79' and phone like 'NA%';

-- ---- LOWER CONFIDENCE: matched by exact plain customer name ----
-- Review this block before running — most plain names in the source file are
-- vendors/mechanics, not customers, but an exact name match against a customer
-- with a placeholder phone is very unlikely to be coincidental. Comment out any
-- lines you are not confident about.
update customers set phone = '8037931597', updated_at = now() where upper(trim(name)) = 'CUSTOMER 7' and phone like 'NA%';
update customers set phone = '8610394494', updated_at = now() where upper(trim(name)) = 'PRIYA TRADERS' and phone like 'NA%';
update customers set phone = '9952734920', updated_at = now() where upper(trim(name)) = 'GAS WELDING SURESH' and phone like 'NA%';
update customers set phone = '9445983716', updated_at = now() where upper(trim(name)) = 'ADDBLUE PUMP KPM' and phone like 'NA%';
update customers set phone = '8088812280', updated_at = now() where upper(trim(name)) = 'LED LIGHT BANGALORE' and phone like 'NA%';
update customers set phone = '8344566228', updated_at = now() where upper(trim(name)) = 'FRIENDS KPM' and phone like 'NA%';
update customers set phone = '9677801423', updated_at = now() where upper(trim(name)) = 'YUVARAJ MECHANIC KPM' and phone like 'NA%';
update customers set phone = '9446890143', updated_at = now() where upper(trim(name)) = 'SUNIL MEENAKSHI MEDICAL PRO' and phone like 'NA%';
update customers set phone = '9952783406', updated_at = now() where upper(trim(name)) = 'MOORTHY ACTIVE DRIVER KPM' and phone like 'NA%';
update customers set phone = '9841771115', updated_at = now() where upper(trim(name)) = 'SASI AC WORK' and phone like 'NA%';
update customers set phone = '9003603528', updated_at = now() where upper(trim(name)) = 'BAI SCRAP ARKOT' and phone like 'NA%';
update customers set phone = '9443729031', alt_phone = coalesce(alt_phone, '9789411094'), updated_at = now() where upper(trim(name)) = 'PICHANDI HEAD WORK VELLORE' and phone like 'NA%';
update customers set phone = '9025055930', updated_at = now() where upper(trim(name)) = 'VERNA' and phone like 'NA%';
update customers set phone = '9080575994', alt_phone = coalesce(alt_phone, '9080544822'), updated_at = now() where upper(trim(name)) = 'SURYA MECHANIC' and phone like 'NA%';
update customers set phone = '9443221273', updated_at = now() where upper(trim(name)) = 'MM TOOLS VELLORE' and phone like 'NA%';
update customers set phone = '8939660227', updated_at = now() where upper(trim(name)) = 'SRINI KPM SSV' and phone like 'NA%';
update customers set phone = '9626260392', alt_phone = coalesce(alt_phone, '9629699242'), updated_at = now() where upper(trim(name)) = 'BAI SCRAP KPM' and phone like 'NA%';
update customers set phone = '9443689973', updated_at = now() where upper(trim(name)) = 'LAKSHMI CAR DECORS' and phone like 'NA%';
update customers set phone = '8682861586', updated_at = now() where upper(trim(name)) = 'NOZZLE SERVICE AUTO NAGAR' and phone like 'NA%';
update customers set phone = '9751370072', updated_at = now() where upper(trim(name)) = 'YUSAF BAI' and phone like 'NA%';
update customers set phone = '9094755581', updated_at = now() where upper(trim(name)) = 'AR CAR ACCESSORIES CHENNAI' and phone like 'NA%';
update customers set phone = '8056276642', updated_at = now() where upper(trim(name)) = 'SHANKAR SPARE KPM' and phone like 'NA%';
update customers set phone = '9884454259', updated_at = now() where upper(trim(name)) = 'CLASSIC CAR DECOR' and phone like 'NA%';
update customers set phone = '9894227343', updated_at = now() where upper(trim(name)) = 'A TO Z ELECTRICAL' and phone like 'NA%';
update customers set phone = '9994674870', updated_at = now() where upper(trim(name)) = 'RO WATER KPM' and phone like 'NA%';
update customers set phone = '9894803053', updated_at = now() where upper(trim(name)) = 'PATTARAI KPM DAMU' and phone like 'NA%';
update customers set phone = '8870986379', updated_at = now() where upper(trim(name)) = 'DOOR PAD LEATHER' and phone like 'NA%';
update customers set phone = '9943541430', updated_at = now() where upper(trim(name)) = 'FIESTA' and phone like 'NA%';
update customers set phone = '8925853767', updated_at = now() where upper(trim(name)) = 'MAN POWER RECRUITER' and phone like 'NA%';
update customers set phone = '9894545095', updated_at = now() where upper(trim(name)) = 'AADEE CAR CARE KPM' and phone like 'NA%';
update customers set phone = '9790087813', updated_at = now() where upper(trim(name)) = 'MURALI HELPER' and phone like 'NA%';
update customers set phone = '9566125180', updated_at = now() where upper(trim(name)) = 'RATHIMEENA PARCEL' and phone like 'NA%';
update customers set phone = '7200529511', updated_at = now() where upper(trim(name)) = 'VIGNESH BULDING PLAN' and phone like 'NA%';
update customers set phone = '8838083281', updated_at = now() where upper(trim(name)) = 'JAYASAKTHIVEL PRASIDENT BNI' and phone like 'NA%';
update customers set phone = '9841450626', updated_at = now() where upper(trim(name)) = 'RADHIKA TILES BNI' and phone like 'NA%';
update customers set phone = '9941757087', updated_at = now() where upper(trim(name)) = 'VISHAL TAX BNI' and phone like 'NA%';
update customers set phone = '8122444780', updated_at = now() where upper(trim(name)) = 'VIJAY CCTV BNI' and phone like 'NA%';
update customers set phone = '9597668900', updated_at = now() where upper(trim(name)) = 'SURJIT MEDIA SERVICE BNI' and phone like 'NA%';
update customers set phone = '8220118140', updated_at = now() where upper(trim(name)) = 'SPN TYRES' and phone like 'NA%';
update customers set phone = '9962890099', updated_at = now() where upper(trim(name)) = 'PURUSOTH LIC BNI' and phone like 'NA%';
update customers set phone = '8248850575', alt_phone = coalesce(alt_phone, '9597246149'), updated_at = now() where upper(trim(name)) = 'PAINTER UMAR' and phone like 'NA%';
update customers set phone = '9626623644', updated_at = now() where upper(trim(name)) = 'MARI MALIKAI STORE BNI' and phone like 'NA%';
update customers set phone = '6381665268', updated_at = now() where upper(trim(name)) = 'MGR SILKS OWNER' and phone like 'NA%';
update customers set phone = '7200602932', updated_at = now() where upper(trim(name)) = 'MANI CRYPTO KPM' and phone like 'NA%';
update customers set phone = '8122434897', updated_at = now() where upper(trim(name)) = 'MARUTI SABARI' and phone like 'NA%';
update customers set phone = '8909853333', updated_at = now() where upper(trim(name)) = 'ML MAHINDRA PARTS KPM' and phone like 'NA%';
update customers set phone = '9787122117', updated_at = now() where upper(trim(name)) = 'PANT ORDER' and phone like 'NA%';
update customers set phone = '9500594358', alt_phone = coalesce(alt_phone, '9952379008'), updated_at = now() where upper(trim(name)) = 'TAJ TOOLS VELLORE' and phone like 'NA%';
update customers set phone = '6380354713', updated_at = now() where upper(trim(name)) = 'TINKER GVS' and phone like 'NA%';
update customers set phone = '8124192585', updated_at = now() where upper(trim(name)) = 'PAINTER WALAJA' and phone like 'NA%';
update customers set phone = '9791707946', updated_at = now() where upper(trim(name)) = 'BALA JEWL IOB' and phone like 'NA%';
update customers set phone = '9244655240', updated_at = now() where upper(trim(name)) = 'MANAGER' and phone like 'NA%';
update customers set phone = '8681939393', updated_at = now() where upper(trim(name)) = 'RUTHIRA KUMAR ARCHITECT BNI' and phone like 'NA%';
update customers set phone = '7010870088', updated_at = now() where upper(trim(name)) = 'BOLERO' and phone like 'NA%';
update customers set phone = '9363136623', updated_at = now() where upper(trim(name)) = 'BALOON DECARATION' and phone like 'NA%';
update customers set phone = '9176499494', updated_at = now() where upper(trim(name)) = 'PPF TEFLON COACHING' and phone like 'NA%';
update customers set phone = '9211999866', updated_at = now() where upper(trim(name)) = 'GO MECHANIC' and phone like 'NA%';
update customers set phone = '7639696111', updated_at = now() where upper(trim(name)) = 'SAKTHIVEL TRAVELS BNI' and phone like 'NA%';
update customers set phone = '8778866820', updated_at = now() where upper(trim(name)) = 'ASWIN ADD SHOOT' and phone like 'NA%';
update customers set phone = '9994775828', updated_at = now() where upper(trim(name)) = 'DRIVER SEENU' and phone like 'NA%';
update customers set phone = '6374366711', updated_at = now() where upper(trim(name)) = 'BANNER PASTING' and phone like 'NA%';
update customers set phone = '9840333377', updated_at = now() where upper(trim(name)) = 'RAGU REAL ESTATE BNI' and phone like 'NA%';
update customers set phone = '6374371710', updated_at = now() where upper(trim(name)) = 'KANCHI MECHANIC' and phone like 'NA%';
update customers set phone = '8401233144', updated_at = now() where upper(trim(name)) = 'VERNA AC' and phone like 'NA%';
update customers set phone = '9442412626', updated_at = now() where upper(trim(name)) = 'TOOLS VELLORE' and phone like 'NA%';
update customers set phone = '9597376691', updated_at = now() where upper(trim(name)) = 'DRIVER SELVARAJ BNI' and phone like 'NA%';
update customers set phone = '9003035493', updated_at = now() where upper(trim(name)) = '+91 90030 35493' and phone like 'NA%';
update customers set phone = '8667316192', updated_at = now() where upper(trim(name)) = 'MANN + FILTER' and phone like 'NA%';
update customers set phone = '9385678001', updated_at = now() where upper(trim(name)) = 'LOKESH SOLAR BNI' and phone like 'NA%';
update customers set phone = '7826077162', updated_at = now() where upper(trim(name)) = 'FINANCE RAMKUMAR' and phone like 'NA%';
update customers set phone = '9360481796', updated_at = now() where upper(trim(name)) = 'RAKESH BNI' and phone like 'NA%';
update customers set phone = '9790706204', updated_at = now() where upper(trim(name)) = 'MURALI MECHANIC JOB' and phone like 'NA%';
update customers set phone = '9003604577', updated_at = now() where upper(trim(name)) = 'GLASS SHOP' and phone like 'NA%';
update customers set phone = '9363621362', updated_at = now() where upper(trim(name)) = 'AC COMPRESSOR PUDUPETTAI' and phone like 'NA%';
update customers set phone = '7639808440', updated_at = now() where upper(trim(name)) = 'PAINTER NAMAKKAL' and phone like 'NA%';
update customers set phone = '9994284304', updated_at = now() where upper(trim(name)) = 'TRAVELS BIG' and phone like 'NA%';
update customers set phone = '9092953523', updated_at = now() where upper(trim(name)) = 'MURUGAN PAINT CHENNAI' and phone like 'NA%';
update customers set phone = '8056381726', updated_at = now() where upper(trim(name)) = 'SHANKAR HOME' and phone like 'NA%';
update customers set phone = '9600983306', updated_at = now() where upper(trim(name)) = 'AC SPARE CHENNAI' and phone like 'NA%';
update customers set phone = '7695992855', updated_at = now() where upper(trim(name)) = 'CASTROL OIL' and phone like 'NA%';
update customers set phone = '8754334359', updated_at = now() where upper(trim(name)) = 'MUTHU SCRAP TIRUPUR' and phone like 'NA%';
update customers set phone = '9940075107', updated_at = now() where upper(trim(name)) = 'MAHADEV PARTS VELLORE' and phone like 'NA%';
update customers set phone = '9994485058', updated_at = now() where upper(trim(name)) = 'ETIOS LIVA' and phone like 'NA%';
update customers set phone = '7373394586', updated_at = now() where upper(trim(name)) = 'RAMESH AC MECHANIC' and phone like 'NA%';
update customers set phone = '6382586985', updated_at = now() where upper(trim(name)) = 'NITHYA SILKS BNI' and phone like 'NA%';
update customers set phone = '9585634454', updated_at = now() where upper(trim(name)) = 'BALAJI WATER WASH' and phone like 'NA%';
update customers set phone = '9025661884', updated_at = now() where upper(trim(name)) = 'SHELL OIL JEEVA KPM' and phone like 'NA%';
update customers set phone = '9840757778', updated_at = now() where upper(trim(name)) = 'PUDUPETTAI SPARE ENGINE' and phone like 'NA%';
update customers set phone = '9043633653', updated_at = now() where upper(trim(name)) = 'BARATH POLICE KPM TALUK' and phone like 'NA%';
update customers set phone = '9047331168', updated_at = now() where upper(trim(name)) = 'ASHWIN CAR DECORS' and phone like 'NA%';
update customers set phone = '8610562876', updated_at = now() where upper(trim(name)) = 'MONOKARAN PUDUPETTAI' and phone like 'NA%';
update customers set phone = '9865264883', updated_at = now() where upper(trim(name)) = 'SHEYAM FATHER' and phone like 'NA%';
update customers set phone = '9629957078', updated_at = now() where upper(trim(name)) = 'NVR PARCEL KPM' and phone like 'NA%';
update customers set phone = '9940087833', updated_at = now() where upper(trim(name)) = 'PAINTER SATHISH ASPHA' and phone like 'NA%';
update customers set phone = '9384815950', updated_at = now() where upper(trim(name)) = '5K IYSWAR' and phone like 'NA%';
update customers set phone = '9677199666', updated_at = now() where upper(trim(name)) = 'AASIF ECM' and phone like 'NA%';
update customers set phone = '8122098061', updated_at = now() where upper(trim(name)) = 'SAMUEL PARTHIBAN JOB REQUEST' and phone like 'NA%';
update customers set phone = '9790440802', updated_at = now() where upper(trim(name)) = 'BALAMURUGAN PATTARAI VELLORE' and phone like 'NA%';
update customers set phone = '9150265769', updated_at = now() where upper(trim(name)) = 'OLD SPARE MADURAVOYAL' and phone like 'NA%';
update customers set phone = '9003838849', updated_at = now() where upper(trim(name)) = 'NANDHA ELECTRIC WORK' and phone like 'NA%';
update customers set phone = '9087240111', updated_at = now() where upper(trim(name)) = 'VERITOS FINANCE' and phone like 'NA%';
update customers set phone = '6374816177', updated_at = now() where upper(trim(name)) = 'FINANCE' and phone like 'NA%';
update customers set phone = '9841823248', updated_at = now() where upper(trim(name)) = 'CNG SANTHOSH RANIPET' and phone like 'NA%';
update customers set phone = '9629730457', updated_at = now() where upper(trim(name)) = 'MOHAN RAJ FALSE SEALING BNI' and phone like 'NA%';
update customers set phone = '9500903399', updated_at = now() where upper(trim(name)) = 'KEY REPAIR MARKET KPM' and phone like 'NA%';
update customers set phone = '9629628804', alt_phone = coalesce(alt_phone, '9566682077'), updated_at = now() where upper(trim(name)) = 'JEEVITHA MOBILE SALES SERVICE BNI' and phone like 'NA%';
update customers set phone = '7010443081', updated_at = now() where upper(trim(name)) = 'BATTERY AMARON' and phone like 'NA%';
update customers set phone = '8220280388', updated_at = now() where upper(trim(name)) = 'JAYAKUMAR SUBROS AC SERVICE' and phone like 'NA%';
update customers set phone = '9159012629', updated_at = now() where upper(trim(name)) = 'VIJAY SVS' and phone like 'NA%';
update customers set phone = '9790218721', updated_at = now() where upper(trim(name)) = 'LOGU HELPER' and phone like 'NA%';
update customers set phone = '6385720267', updated_at = now() where upper(trim(name)) = 'ETIOS' and phone like 'NA%';
update customers set phone = '9962376157', updated_at = now() where upper(trim(name)) = 'JAGAN PUDUPETTAI' and phone like 'NA%';
update customers set phone = '9944636255', updated_at = now() where upper(trim(name)) = 'STG BOX SERVICE GANESH THIRUTHANI' and phone like 'NA%';
update customers set phone = '9698963002', updated_at = now() where upper(trim(name)) = 'MASILAMANI MAHINDRA' and phone like 'NA%';
update customers set phone = '9994162243', updated_at = now() where upper(trim(name)) = 'CNG CONVERSION' and phone like 'NA%';
update customers set phone = '9344819197', updated_at = now() where upper(trim(name)) = 'SAYO TOURS' and phone like 'NA%';
update customers set phone = '8883229472', updated_at = now() where upper(trim(name)) = 'SHANKAR MECHANIC' and phone like 'NA%';
update customers set phone = '9789349231', updated_at = now() where upper(trim(name)) = 'MUTHUMANI SOFTWARE SOLUTIONS BNI' and phone like 'NA%';
update customers set phone = '7339477926', updated_at = now() where upper(trim(name)) = 'OWNER 2' and phone like 'NA%';
update customers set phone = '7418682298', alt_phone = coalesce(alt_phone, '6385317307'), updated_at = now() where upper(trim(name)) = 'VARA MAHALAKSHMI TEXTILE' and phone like 'NA%';
update customers set phone = '8825629085', updated_at = now() where upper(trim(name)) = 'ARUN KUMAR AC BNI' and phone like 'NA%';
update customers set phone = '8778143486', updated_at = now() where upper(trim(name)) = 'SABITHA GIRI RO WATER BNI' and phone like 'NA%';
update customers set phone = '9894545764', updated_at = now() where upper(trim(name)) = 'SRI AUTOMOBILE' and phone like 'NA%';
update customers set phone = '9655332889', updated_at = now() where upper(trim(name)) = 'ST COURIER ORIKAI' and phone like 'NA%';
update customers set phone = '8939651184', updated_at = now() where upper(trim(name)) = 'OWNER' and phone like 'NA%';
update customers set phone = '9751361117', updated_at = now() where upper(trim(name)) = 'PANDIYAN POLICE SADAVARAM' and phone like 'NA%';
update customers set phone = '7200042284', updated_at = now() where upper(trim(name)) = 'SURESH CHIT FUNDS BNI' and phone like 'NA%';
update customers set phone = '9787549179', updated_at = now() where upper(trim(name)) = 'MY NUMBER' and phone like 'NA%';
update customers set phone = '9521296993', updated_at = now() where upper(trim(name)) = 'MAHALAXMI AUTO PARTS VELLORE' and phone like 'NA%';
update customers set phone = '9443643159', updated_at = now() where upper(trim(name)) = 'RAGUNATHAN REAL ESTATE BNI' and phone like 'NA%';
update customers set phone = '9952446623', updated_at = now() where upper(trim(name)) = 'PANDIYAN REAL ESTATE CHENGALPATTU' and phone like 'NA%';
update customers set phone = '9629272751', updated_at = now() where upper(trim(name)) = 'GOUTHAM TAILORING BNI' and phone like 'NA%';
update customers set phone = '7373130625', updated_at = now() where upper(trim(name)) = 'BALA CHANDER ADVERTISEMENT BNI' and phone like 'NA%';
update customers set phone = '9944345435', updated_at = now() where upper(trim(name)) = 'SHANKAR ACTING DRIVER' and phone like 'NA%';
update customers set phone = '9994191547', updated_at = now() where upper(trim(name)) = '5K CAR CARE OWNER' and phone like 'NA%';
update customers set phone = '7094760764', alt_phone = coalesce(alt_phone, '9360436113'), updated_at = now() where upper(trim(name)) = 'PRINTER SERVICE' and phone like 'NA%';
update customers set phone = '9894761233', updated_at = now() where upper(trim(name)) = 'SUN TURBO VELLORE' and phone like 'NA%';
update customers set phone = '9123568928', updated_at = now() where upper(trim(name)) = 'RAJESH TINKERING' and phone like 'NA%';
update customers set phone = '9382188967', updated_at = now() where upper(trim(name)) = 'ETIOS CUSTOMER NEED SECOND CAR' and phone like 'NA%';
update customers set phone = '9500919290', updated_at = now() where upper(trim(name)) = 'BNI PARTHASARATI CONSTRUCTION' and phone like 'NA%';
update customers set phone = '9994547701', updated_at = now() where upper(trim(name)) = 'IYYAPA' and phone like 'NA%';
update customers set phone = '9566781986', updated_at = now() where upper(trim(name)) = 'MRF WHEEL ALIGNMENT' and phone like 'NA%';
update customers set phone = '9597682468', updated_at = now() where upper(trim(name)) = 'TINKER DASS' and phone like 'NA%';
update customers set phone = '9150155074', updated_at = now() where upper(trim(name)) = '5K MURUGAVEL' and phone like 'NA%';
update customers set phone = '9444767699', updated_at = now() where upper(trim(name)) = 'SIVA CAR AC' and phone like 'NA%';
update customers set phone = '8015488781', updated_at = now() where upper(trim(name)) = 'GPAY SCANNER' and phone like 'NA%';
update customers set phone = '9952377713', updated_at = now() where upper(trim(name)) = 'FINANCE 2' and phone like 'NA%';
update customers set phone = '6374215199', updated_at = now() where upper(trim(name)) = 'KOOVERS HARI KRISHNAN' and phone like 'NA%';
update customers set phone = '8508635741', updated_at = now() where upper(trim(name)) = 'CHOLA DHAKSHAN SERVIOUR' and phone like 'NA%';
update customers set phone = '9123566554', updated_at = now() where upper(trim(name)) = 'PARTHASARATHY CONSTRUCTION BNI' and phone like 'NA%';
update customers set phone = '6382816669', updated_at = now() where upper(trim(name)) = 'KIA PRAVEEN VELLORE' and phone like 'NA%';
update customers set phone = '8778577287', updated_at = now() where upper(trim(name)) = 'BATTERY ORIKAI' and phone like 'NA%';
update customers set phone = '8181027222', alt_phone = coalesce(alt_phone, '9840648649'), updated_at = now() where upper(trim(name)) = 'MAHAVIR VELLORE' and phone like 'NA%';
update customers set phone = '6374770118', updated_at = now() where upper(trim(name)) = 'MOHAN ELECTRICAL WORK' and phone like 'NA%';
update customers set phone = '9551755626', updated_at = now() where upper(trim(name)) = 'ECU SELVIN' and phone like 'NA%';
update customers set phone = '9080045178', updated_at = now() where upper(trim(name)) = 'SHEYAM MOTHER' and phone like 'NA%';
update customers set phone = '8190095980', updated_at = now() where upper(trim(name)) = 'POLICE DRIVER TALK' and phone like 'NA%';
update customers set phone = '9943820221', updated_at = now() where upper(trim(name)) = 'KAMELESH ANBU DRIVING SCHOOL' and phone like 'NA%';
update customers set phone = '8667260906', updated_at = now() where upper(trim(name)) = 'POLICE SI RAJUBAI' and phone like 'NA%';
update customers set phone = '9244860002', updated_at = now() where upper(trim(name)) = 'SRIDHAR SANTHANAM COMPUTER HARDWARE BNI' and phone like 'NA%';
update customers set phone = '6374943035', alt_phone = coalesce(alt_phone, '9445310407'), updated_at = now() where upper(trim(name)) = 'SHANKAR PAINT SHOP' and phone like 'NA%';
update customers set phone = '8870606991', updated_at = now() where upper(trim(name)) = 'PAINTER THYAGARAJAN' and phone like 'NA%';
update customers set phone = '9894632600', updated_at = now() where upper(trim(name)) = 'PETROL BUNK PURUSOTH' and phone like 'NA%';
update customers set phone = '6382666097', updated_at = now() where upper(trim(name)) = 'SURYA MECH 2' and phone like 'NA%';
update customers set phone = '9087223579', updated_at = now() where upper(trim(name)) = 'SHALINI ELECTRICAL' and phone like 'NA%';
update customers set phone = '9025405460', updated_at = now() where upper(trim(name)) = 'SIVANANTHA PAINT SHOP' and phone like 'NA%';
update customers set phone = '6385565019', updated_at = now() where upper(trim(name)) = 'AUTO SRI' and phone like 'NA%';
update customers set phone = '9943382328', updated_at = now() where upper(trim(name)) = 'CAR SCRAB BAI KPM' and phone like 'NA%';
update customers set phone = '9361621675', updated_at = now() where upper(trim(name)) = 'GST FILING' and phone like 'NA%';
update customers set phone = '6379176934', updated_at = now() where upper(trim(name)) = 'VIJAY MECHANIC' and phone like 'NA%';
update customers set phone = '8098009767', updated_at = now() where upper(trim(name)) = 'JUST DIAL KRITHIK' and phone like 'NA%';
update customers set phone = '9445145002', updated_at = now() where upper(trim(name)) = 'NET CONNECTION' and phone like 'NA%';
update customers set phone = '9629641208', updated_at = now() where upper(trim(name)) = 'ASHOK KUMAR INTERIOR BNI' and phone like 'NA%';
update customers set phone = '9491105074', updated_at = now() where upper(trim(name)) = 'MURUGAVEL DRIVER' and phone like 'NA%';
update customers set phone = '8015910784', updated_at = now() where upper(trim(name)) = 'NATIONAL STEERING BOX SERVICE KPM' and phone like 'NA%';
update customers set phone = '8825804551', updated_at = now() where upper(trim(name)) = 'SRI ANAND' and phone like 'NA%';
update customers set phone = '9791612431', updated_at = now() where upper(trim(name)) = 'SIVA CAR SELLING' and phone like 'NA%';
update customers set phone = '9597648979', updated_at = now() where upper(trim(name)) = 'SIVA SISTER' and phone like 'NA%';
update customers set phone = '7200639336', updated_at = now() where upper(trim(name)) = 'INDICA CHEYYAR' and phone like 'NA%';
update customers set phone = '9994167009', updated_at = now() where upper(trim(name)) = '99941 67009' and phone like 'NA%';
update customers set phone = '7904043083', updated_at = now() where upper(trim(name)) = 'MADAM' and phone like 'NA%';
update customers set phone = '9087766822', updated_at = now() where upper(trim(name)) = 'A LTO Z JEEVA' and phone like 'NA%';
update customers set phone = '9543668090', updated_at = now() where upper(trim(name)) = 'UDAYAKUMAR' and phone like 'NA%';
update customers set phone = '9629413921', updated_at = now() where upper(trim(name)) = 'ASHOK BUILDER' and phone like 'NA%';
update customers set phone = '8655826690', updated_at = now() where upper(trim(name)) = 'KOTAK INSURANCE' and phone like 'NA%';
update customers set phone = '9585742842', updated_at = now() where upper(trim(name)) = 'SARAVANA ELECTRICALS' and phone like 'NA%';
update customers set phone = '6380158936', updated_at = now() where upper(trim(name)) = 'BNI VIGNESH PRINTING' and phone like 'NA%';
update customers set phone = '9841031403', updated_at = now() where upper(trim(name)) = 'IYER BEHIND' and phone like 'NA%';
update customers set phone = '9444006452', updated_at = now() where upper(trim(name)) = 'MADHAVAN PUDUPETTAI' and phone like 'NA%';
update customers set phone = '9900889977', updated_at = now() where upper(trim(name)) = 'CLINIC KPM' and phone like 'NA%';
update customers set phone = '9176931360', updated_at = now() where upper(trim(name)) = 'GOPAL T BOARD ADMIN' and phone like 'NA%';
update customers set phone = '7708080999', updated_at = now() where upper(trim(name)) = 'NEW INDIA MURALI' and phone like 'NA%';
update customers set phone = '8220111626', updated_at = now() where upper(trim(name)) = 'KANCHI TILES RADHIKA MEDAM BNI' and phone like 'NA%';
update customers set phone = '9994174119', alt_phone = coalesce(alt_phone, '9865569765'), updated_at = now() where upper(trim(name)) = 'RADIATOR SERVICE' and phone like 'NA%';
update customers set phone = '9840935600', updated_at = now() where upper(trim(name)) = 'BAI PUDUPETTAI ENGINE' and phone like 'NA%';
update customers set phone = '9788707322', updated_at = now() where upper(trim(name)) = 'EB VICTOR' and phone like 'NA%';
update customers set phone = '9442686917', updated_at = now() where upper(trim(name)) = 'SEKAR PRITING BNI' and phone like 'NA%';
update customers set phone = '8610919654', updated_at = now() where upper(trim(name)) = 'BNI PARITHI GIFTS' and phone like 'NA%';
update customers set phone = '6383740990', updated_at = now() where upper(trim(name)) = 'PRAVEEN DIGITAL MARKETING' and phone like 'NA%';
update customers set phone = '9840498959', updated_at = now() where upper(trim(name)) = 'RUBBING POLISHING' and phone like 'NA%';
update customers set phone = '9789655704', updated_at = now() where upper(trim(name)) = 'DOOR MECHANIC KPM' and phone like 'NA%';
update customers set phone = '8925354892', alt_phone = coalesce(alt_phone, '9626060479'), updated_at = now() where upper(trim(name)) = 'MUKILAN ELECTRIC' and phone like 'NA%';
update customers set phone = '6381941458', updated_at = now() where upper(trim(name)) = 'SUJITH ADD' and phone like 'NA%';
update customers set phone = '9790023290', updated_at = now() where upper(trim(name)) = 'DHANDAPANI SURVEYOR' and phone like 'NA%';
update customers set phone = '9626529158', updated_at = now() where upper(trim(name)) = 'KEY POINT KPM' and phone like 'NA%';
update customers set phone = '9042339336', updated_at = now() where upper(trim(name)) = 'VIDEO SHOOT SENTHIL' and phone like 'NA%';
update customers set phone = '9943424061', updated_at = now() where upper(trim(name)) = 'YES KANCHIPURAM' and phone like 'NA%';
update customers set phone = '9566356950', updated_at = now() where upper(trim(name)) = 'KRISHNA JOB NEED' and phone like 'NA%';
update customers set phone = '7094500197', updated_at = now() where upper(trim(name)) = 'CAR NEED' and phone like 'NA%';
update customers set phone = '9597909815', updated_at = now() where upper(trim(name)) = 'JG AUTOMOBILE SENSOR VELLORE' and phone like 'NA%';
update customers set phone = '9789142007', updated_at = now() where upper(trim(name)) = 'SEKAR POLICE SI SRIPERUMBUDUR' and phone like 'NA%';
update customers set phone = '8610189752', updated_at = now() where upper(trim(name)) = 'APPU PAINTER' and phone like 'NA%';
update customers set phone = '8124592650', alt_phone = coalesce(alt_phone, '9629517759'), updated_at = now() where upper(trim(name)) = 'SURYA BLOCK PEARL' and phone like 'NA%';
update customers set phone = '9566870403', updated_at = now() where upper(trim(name)) = 'SRI SIVA' and phone like 'NA%';
update customers set phone = '9500406918', updated_at = now() where upper(trim(name)) = 'SANTHOSH SPORTS BNI' and phone like 'NA%';
update customers set phone = '9994505768', updated_at = now() where upper(trim(name)) = 'SINGARAVELAN SOFTWARE BNI' and phone like 'NA%';
update customers set phone = '8667830853', updated_at = now() where upper(trim(name)) = 'SATHISH KUMAR BNI METAL CONSTRUCTION' and phone like 'NA%';
update customers set phone = '9150942337', updated_at = now() where upper(trim(name)) = 'HDFC BANK LAWER' and phone like 'NA%';
update customers set phone = '9790106164', updated_at = now() where upper(trim(name)) = 'BNI VANITHA JOY' and phone like 'NA%';
update customers set phone = '7708054392', updated_at = now() where upper(trim(name)) = 'SCRAB WALAJABATH' and phone like 'NA%';

commit;